# Generated by Django 3.2.4 on 2021-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
