# Generated by Django 3.2.4 on 2021-07-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_delete_poke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='poke.user')),
                ('origin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokers', to='poke.user')),
            ],
        ),
    ]
